language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
env:
  global:
    - COVERALLS_REPO_TOKEN=22wDc8ykTjwGiirppxb9WD7izGJXJmiAb
before_install:
- chmod +x gradlew
- chmod +rx app
skip_cleanup: true
script:
- export COVERALLS_REPO_TOKEN=22wDc8ykTjwGiirppxb9WD7izGJXJmiAb
- export CI=true
- ./gradlew jacocoTestReport
after_success:
- ./gradlew coveralls