language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
before_install:
- chmod +x gradlew
- chmod +rx app
skip_cleanup: true
script:
- ./gradlew test